/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bankapp;

import com.sun.glass.events.KeyEvent;
import java.awt.Point;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author KINGSLEY
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    
    Connection conn;
    
    public login() {
        initComponents();
    }
    
    //constructor with connection object 
    public login(Connection obj){
        initComponents();
        conn = obj;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toSignUp = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        usrNumber = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        signUp = new javax.swing.JLabel();
        pinNumber = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        toSignUp.setBackground(new java.awt.Color(102, 102, 102));
        toSignUp.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                toSignUpMouseDragged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Century Schoolbook", 0, 11)); // NOI18N
        jLabel1.setText("Usr Number :");

        usrNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                usrNumberKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Century Schoolbook", 0, 11)); // NOI18N
        jLabel2.setText("Pin :");

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        signUp.setFont(new java.awt.Font("Century Schoolbook", 0, 11)); // NOI18N
        signUp.setText("Click to Sign up");
        signUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signUpMouseClicked(evt);
            }
        });

        pinNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pinNumberKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout toSignUpLayout = new javax.swing.GroupLayout(toSignUp);
        toSignUp.setLayout(toSignUpLayout);
        toSignUpLayout.setHorizontalGroup(
            toSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toSignUpLayout.createSequentialGroup()
                .addGroup(toSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pinNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(toSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(toSignUpLayout.createSequentialGroup()
                            .addGap(25, 25, 25)
                            .addComponent(usrNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(toSignUpLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(toSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(toSignUpLayout.createSequentialGroup()
                                    .addComponent(signUp, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        toSignUpLayout.setVerticalGroup(
            toSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toSignUpLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(usrNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pinNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addGroup(toSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signUp)
                    .addComponent(jButton1))
                .addContainerGap(128, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\KINGSLEY\\Documents\\NetBeansProjects\\BankApp\\2524-200.png")); // NOI18N

        exit.setFont(new java.awt.Font("Century Schoolbook", 0, 12)); // NOI18N
        exit.setText(" Exit");
        exit.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(toSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toSignUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUpMouseClicked
        // TODO add your handling code here:
        signUp newSign = new signUp(conn);
        newSign.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_signUpMouseClicked

    //handles user login 
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Statement stmt;
        int usrNum = 0;
        int pinNum = 0;
        String userUsr = usrNumber.getText();
        String userPin = pinNumber.getText();
            
            try{
                usrNum = Integer.parseInt(userUsr);
                pinNum = Integer.parseInt(userPin);
            
            }
            catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null, "no entry");
            }
        
        try {
            stmt = conn.createStatement();
            String sql = "SELECT usrNo, pin from userInfo where usrNo = "+ usrNum + " " ;
            ResultSet rs = stmt.executeQuery(sql);
            
            //checks if user exists
        if (rs == null){
                JOptionPane.showMessageDialog(null,"Not A USER");
            }
        else{
            //checks if user details are correct
            int usr = 0;
            int pin = 0;
            while(rs.next()){
            usr = Integer.parseInt(rs.getString("usrNo")) ;
            pin = Integer.parseInt(rs.getString("pin"));
                    }
            if (usrNum == usr && pinNum == pin){
                
               String Name = null;
               String sName = null;
               double aBalance = 0;
               double mBalance = 0;
               String mNumber = null;                
                
               String sqlOne = "Select FName,LName,acctBalance,mobileBalance,mobileNumber from userInfo where usrNo = " + usrNum + " " ;
               ResultSet rsOne = stmt.executeQuery(sqlOne);
         
               
               while(rsOne.next()){
                   Name = rsOne.getString("FName");
                   sName = rsOne.getString("LName");
                   aBalance = rsOne.getDouble("acctBalance");
                   mBalance = rsOne.getDouble("mobileBalance");
                   mNumber = rsOne.getString("mobileNumber");   
               }
               
               account usrAccount = new account(Name, sName, aBalance, mBalance, mNumber, usr, pin);
               
               
               
                home usrHome = new home(usrAccount,conn); // creates an obj of home page
                usrHome.setVisible(true);
                this.dispose();
            }
            
            else{
                JOptionPane.showMessageDialog(null,"Wrong usr or pin");   
            }
            }
        
        } catch (SQLException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    //exits the program and closes the connetion
    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
              System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void pinNumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pinNumberKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)) ||(c == KeyEvent.VK_BACKSPACE)
                || c == KeyEvent.VK_DELETE){
            getToolkit().beep();
            evt.consume();
        }
        
        
    }//GEN-LAST:event_pinNumberKeyTyped

    private void usrNumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usrNumberKeyTyped
         char c = evt.getKeyChar();
        if(!(Character.isDigit(c)) ||(c == KeyEvent.VK_BACKSPACE)
                || c == KeyEvent.VK_DELETE){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_usrNumberKeyTyped

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        Point p = evt.getLocationOnScreen();
        this.setLocation(p);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void toSignUpMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toSignUpMouseDragged
        Point p = evt.getLocationOnScreen();
        this.setLocation(p);
    }//GEN-LAST:event_toSignUpMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel exit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField pinNumber;
    private javax.swing.JLabel signUp;
    private javax.swing.JPanel toSignUp;
    private javax.swing.JTextField usrNumber;
    // End of variables declaration//GEN-END:variables
}
